### ISSUE TITLE
Broken compatibility with Iridium on from ATO and IC2

### ISSUE THREAD

**Issue by MPThLee** [AllTheMods/VolcanoBlock#100]
![image](https://github.com/AllTheMods/VolcanoBlock/assets/26970092/d14bd988-4cbd-42df-8a27-510e778b7f55)
Ic2 iridium ore is not compatible with ATO's iridium ore. as ic2 iridium is not minable and only crafted from uu-matter so it is might be ok.

![image](https://github.com/AllTheMods/VolcanoBlock/assets/26970092/0947322f-b1d0-4942-9538-0c2dd6e7039c)
The advanced Solars Classic's crafting recipe requires ATO's Iridium ingot. and not from ASC's Iridium ingot (that made with ic2 iridium ore). And originally this should be ASC's Iridium.

This should be fixed. Be compatible each other, or completely no compatible.
Also, should care about the ic2's loneliness too.

**Comment by oly2o6** [comment]
Hello! So thank you for bringing this issue to our attention, we will decide how to move forward with this and there should be a change in the next update!

**Comment by oly2o6** [comment]
So we decided that due to the different rarities with ic2 and ato iridiums it will be best to keep them seperated moving forward! With advanced solars being able to use other mods iridium, this is a feature that has been present in multiple ic2 packs over the years, as the iridium in those panels was always cheaper, maybe in the next update ill completely separate it and make it use ic2 iridium but for now, it works and im personally happy with it
