### ISSUE TITLE
Occultism spawning not working with Resource Chickens

### ISSUE THREAD

**Issue by WeeBoots** [AllTheMods/VolcanoBlock#109]
I've raised this with the Occultism mod owner as well and have identified that on Minecraft version 1.19.2, Occultism v1.81.1 and Resource Chickens v1.4, it's unable to complete rituals that require a chicken sacrifice. Disabling resource chickens on a separate mod pack duplicate allows Occultism chicken sacrifice rituals to work, however disabling that mod within the ATM8VB pack causes an index error when running, not allowing the error to be shown for more information.

**Comment by Draxial** [comment]
@WeeBoots The only workaround I found is that we on our side, is add the entity_type resourcechickens:chicken to the forge:chicken wwith kubejs, AND use an normal chicken egg from minecraft to spawn the chicken. This might mean that the resourceful chickens mod didn't add the resoursechickens:chicken to the forge tag forge:chicken, but something else weird going on. If the occultism author can make it so it accepts forge:chicken instead of minecraft:chicken, then it'll properly work. I'd assume, if it doesn't; Otherwise if it already uses it, it's resourcefulchickens having something strange going on.

From our side, we can only add the tag manually, and we add a recipe so you can convert a resourcefulchickens:chicken_egg into a minecraft:chicken_egg , which will the chicken from resourceful chickens, but with vanilla features(?) that the occultism mod is expecting. To get the egg in the first place, you'd use the capturing enchantment which you'd need to find as look or traded by a villager, or through enchanting with apotheosis;(the last am not that sure if it's possible). I'll see if it'll be relevant with the team that we add a crafting method to get the resourceful chicken egg(chicken normal egg and 8 chicken essence for example).

https://github.com/AllTheMods/VolcanoBlock/assets/53184989/757a9745-49f4-4129-9ce4-a57f5d3483c4

**Comment by oly2o6** [comment]
Thanks for bringing this to our attention, I will add the tag for the chicken so that the recipe can work as it does above!

**Comment by Draxial** [comment]
@WeeBoots once the new fix is in, please try chickens that were spawned with delightful grass, and if it still doesn't solves it, then please reopen this issue!
