### ISSUE TITLE
Mekanism adding trusted player causes potential issues.

### ISSUE THREAD

**Issue by BenRaguckas** [AllTheMods/VolcanoBlock#96]
Multiplayer; Mekanism-1.19.2-10.3.9.13; VolcanoBlock version-1.0.4
If a mekanism block was placed with trusted protection and broken by a player-A. If said player is added to trusted players the block will break just as the player-A is added. Further more it uses currently held item of the player as reference of breaking. Pickaxes result in block dropping, empty hand in item lost.
When player-A breaks multiple blocks before being trusted only the first block will be broken.

**Comment by BenRaguckas** [comment]
https://www.youtube.com/watch?v=ZjCp1P7K3qw

**Comment by Draxial** [comment]
Might be a weird issue with ftbteams interaction, can you try the same without team claimed chunks?

If still happens then it could be mekanism's, as it seems that it's trying to hold on the event break, but somehow it's keeping the blocked event forever(aka mekanism is denying the action but instead of discarding the action, it keeps on memory/loaded), and when you re-add the person, it lets the breaking pass through
